webtalk_init -webtalk_dir C:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW7/hw7/hw7.sim/sim_1/behav/xsim/xsim.dir/hw7_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb  1 23:32:36 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "367018c8-f0a4-492b-9a68-3ffb8b9833d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0e89f796a9324b1b9016b2b8eb8ef4f2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6952_KB" -context "xsim\\usage"
webtalk_transmit -clientid 810738616 -regid "" -xml C:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW7/hw7/hw7.sim/sim_1/behav/xsim/xsim.dir/hw7_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW7/hw7/hw7.sim/sim_1/behav/xsim/xsim.dir/hw7_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW7/hw7/hw7.sim/sim_1/behav/xsim/xsim.dir/hw7_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
