# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Final Project/code/fpgaKaraoke/fpgaKaraoke.srcs/sources_1/ip/dft_0/dft_0.xci
# IP: The module: 'dft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Final Project/code/fpgaKaraoke/fpgaKaraoke.srcs/sources_1/ip/dft_0/dft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Final Project/code/fpgaKaraoke/fpgaKaraoke.srcs/sources_1/ip/dft_0/dft_0.xci
# IP: The module: 'dft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Final Project/code/fpgaKaraoke/fpgaKaraoke.srcs/sources_1/ip/dft_0/dft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
