# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_2 || ORIG_REF_NAME==design_1_microblaze_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_2/design_1_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_2 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_2/design_1_microblaze_0_axi_intc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_2 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_2/design_1_microblaze_0_xlconcat_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_2 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_2 || ORIG_REF_NAME==design_1_mdm_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_2/design_1_clk_wiz_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_2 || ORIG_REF_NAME==design_1_clk_wiz_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_2/design_1_rst_clk_wiz_1_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_2/design_1_axi_uartlite_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_2 || ORIG_REF_NAME==design_1_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_3 || ORIG_REF_NAME==design_1_mig_7series_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_100M_2/design_1_rst_mig_7series_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_100M_2 || ORIG_REF_NAME==design_1_rst_mig_7series_0_100M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_2/design_1_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_2 || ORIG_REF_NAME==design_1_dlmb_v10_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_2/design_1_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_2 || ORIG_REF_NAME==design_1_ilmb_v10_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_2/design_1_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_2 || ORIG_REF_NAME==design_1_lmb_bram_2} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
