@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Apr 09 15:08:53 -0600 2018
=======
REM Generated by Vivado on Mon Apr 09 11:01:19 -0600 2018
>>>>>>> master
REM SW Build 2018833 on Wed Oct  4 19:58:22 MDT 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim lab4_tb_behav -key {Behavioral:sim_1:Functional:lab4_tb} -tclbatch lab4_tb.tcl -view C:/Users/C19Mark.Demore/Documents/Demore_ECE383/Labs/Lab 4/code/lab4/lab4_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
