# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
# IP: The module: 'design_1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_43/bd_6f02_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_52/bd_6f02_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_55/bd_6f02_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_61/bd_6f02_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_56/bd_6f02_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_57/bd_6f02_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_58/bd_6f02_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_59/bd_6f02_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_60/bd_6f02_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_53/bd_6f02_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_54/bd_6f02_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_49/bd_6f02_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_50/bd_6f02_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_51/bd_6f02_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_44/bd_6f02_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_45/bd_6f02_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_46/bd_6f02_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_47/bd_6f02_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_48/bd_6f02_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_40/bd_6f02_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_41/bd_6f02_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_42/bd_6f02_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_35/bd_6f02_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_36/bd_6f02_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_37/bd_6f02_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_38/bd_6f02_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_39/bd_6f02_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_31/bd_6f02_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_32/bd_6f02_psr0_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_psr_aclk1_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_43/bd_6f02_s00a2s_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_52/bd_6f02_s01a2s_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_55/bd_6f02_m00s2a_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_56/bd_6f02_m00arn_1/bd_6f02_m00arn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_56/bd_6f02_m00arn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_57/bd_6f02_m00rn_1/bd_6f02_m00rn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_57/bd_6f02_m00rn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_58/bd_6f02_m00awn_1/bd_6f02_m00awn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_58/bd_6f02_m00awn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_59/bd_6f02_m00wn_1/bd_6f02_m00wn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_59/bd_6f02_m00wn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_60/bd_6f02_m00bn_1/bd_6f02_m00bn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_60/bd_6f02_m00bn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_53/bd_6f02_sarn_3_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_54/bd_6f02_srn_3_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_44/bd_6f02_sarn_2_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_45/bd_6f02_srn_2_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_46/bd_6f02_sawn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_47/bd_6f02_swn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_48/bd_6f02_sbn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_35/bd_6f02_arsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_36/bd_6f02_rsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_37/bd_6f02_awsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_38/bd_6f02_wsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_39/bd_6f02_bsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_32/bd_6f02_psr0_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_32/bd_6f02_psr0_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_psr_aclk1_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_psr_aclk1_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
# IP: The module: 'design_1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_43/bd_6f02_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_52/bd_6f02_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_55/bd_6f02_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_61/bd_6f02_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_56/bd_6f02_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_57/bd_6f02_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_58/bd_6f02_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_59/bd_6f02_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_60/bd_6f02_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_53/bd_6f02_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_54/bd_6f02_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_49/bd_6f02_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_50/bd_6f02_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_51/bd_6f02_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_44/bd_6f02_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_45/bd_6f02_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_46/bd_6f02_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_47/bd_6f02_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_48/bd_6f02_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_40/bd_6f02_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_41/bd_6f02_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_42/bd_6f02_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_35/bd_6f02_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_36/bd_6f02_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_37/bd_6f02_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_38/bd_6f02_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_39/bd_6f02_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_31/bd_6f02_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_32/bd_6f02_psr0_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_psr_aclk1_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_43/bd_6f02_s00a2s_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_52/bd_6f02_s01a2s_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_55/bd_6f02_m00s2a_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_56/bd_6f02_m00arn_1/bd_6f02_m00arn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_56/bd_6f02_m00arn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_57/bd_6f02_m00rn_1/bd_6f02_m00rn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_57/bd_6f02_m00rn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_58/bd_6f02_m00awn_1/bd_6f02_m00awn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_58/bd_6f02_m00awn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_59/bd_6f02_m00wn_1/bd_6f02_m00wn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_59/bd_6f02_m00wn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_60/bd_6f02_m00bn_1/bd_6f02_m00bn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_60/bd_6f02_m00bn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_53/bd_6f02_sarn_3_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_54/bd_6f02_srn_3_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_44/bd_6f02_sarn_2_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_45/bd_6f02_srn_2_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_46/bd_6f02_sawn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_47/bd_6f02_swn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_48/bd_6f02_sbn_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_35/bd_6f02_arsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_36/bd_6f02_rsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_37/bd_6f02_awsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_38/bd_6f02_wsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_39/bd_6f02_bsw_1_ooc.xdc

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_32/bd_6f02_psr0_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_32/bd_6f02_psr0_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_33/bd_6f02_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_psr_aclk1_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_34/bd_6f02_psr_aclk1_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Homework/HW11/hw11/hw11.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
