# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Lesson Examples/lsn17/lsn17.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2.xci
# IP: The module: 'design_1_lmb_bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Lesson Examples/lsn17/lsn17.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lmb_bram_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Lesson Examples/lsn17/lsn17.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2.xci
# IP: The module: 'design_1_lmb_bram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/C19Mark.Demore/Documents/Demore_ECE383/Lesson Examples/lsn17/lsn17.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lmb_bram_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
